### ISSUE TITLE
BSGenome forge 

### ISSUE THREAD

**Issue by JaykishanJ** [Bioconductor/BSgenomeForge#34] opened 2023-09-13 13:12 UTC
i am trying to forge BSgenome which is not register assembly in UCSC or NCBI 

here is my seed file 

Package: BSgenome.Macuminata.NCBI.Doubled-haploid_Pahang_(DH-Pahang)
Title: Full genome sequence for Musa acuminata subsp. malaccensis (wild Malaysian banana)
Description: Full genome sequence for the eleven chromosomes of Musa acuminata subsp. malaccensis (wild Malaysian banana) Doubled-haploid Pahang (DH-Pahang) provided by NCBI
Version: 2.0.0
organism: Musa acuminata
common_name: Banana
provider: NCBI
provider_version: ASM31385v2
release_date: 2012/10
release_name: Doubled-haploid Pahang (DH-Pahang) (strain)	
source_url: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000313855.2/
organism_biocview: Musa_acuminata
BSgenomeObjname: Macuminata
seqnames: c("NC_025202.1","NC_025203.1","NC_025204.1","NC_025205.1","NC_025206.1","NC_025207.1","NC_025208.1","NC_025209.1","NC_025210.1","NC_025211.1","NC_025212.1")
seqs_srcdir: /data/003_NGS_research_projects/NGS_220464_Methylation/data/genome/seqs_srcdir

and this is the code i am using 

forgeBSgenomeDataPkg("BSgenome.Macuminata.NCBI-seed")

while perorming this i am getting error 

> forgeBSgenomeDataPkg("BSgenome.Vcholerae.NCBI.N16961-seed")
Error in .make_Seqinfo_from_genome(genome) :
  "ASM674v1" is not a registered NCBI assembly or UCSC genome (use
  registered_NCBI_assemblies() or registered_UCSC_genomes() to list the
  NCBI or UCSC assemblies/genomes currently registered in the
  GenomeInfoDb package)
In addition: Warning message:
In forgeBSgenomeDataPkg(y, seqs_srcdir = seqs_srcdir, destdir = destdir,  :
  field 'release_name' is deprecated

could you please guide me for the same how to solve this 

or is that a case that if assembly is not register then we cant able to perform forgeBSgenome please guide me through the possible solution thank you 

@hpages @kakopo @jwokaty @lwaldron @LiNk-NY

**Comment by hpages** [comment] 2023-09-13 23:37
Hi,

The new [**BSgenomeForge**](https://bioconductor.org/packages/BSgenomeForge) package makes this very easy:
```
library(BSgenomeForge)

forgeBSgenomeDataPkgFromNCBI("GCF_000313855.2",
             pkg_maintainer="Jane Doe <janedoe@gmail.com>",
             organism="Musa acuminata subsp. malaccensis",
             circ_seqs=character(0))
```
This takes about 4 min on my laptop and creates the **BSgenome.Mmalaccensis.NCBI.ASM31385v2** package in the current directory (please note that R package names cannot contain the underscore `_`).

See the _How to use the BSgenomeForge package to forge a BSgenome data package_ vignette for more information.

Cheers,
H.

**Comment by JaykishanJ** [comment] 2023-09-14 03:08
Thank you for your response still I have few questions for my genome which I am trying to forge it's not in 2bit format also if i give single .gz file of genome is that fine or I have 11 chromosome so I have to give individual chromosome in fasta can you please guide me through genome format

**Comment by hpages** [comment] 2023-09-14 16:20
Hmm... for some reason this last comment of yours does not show up on 
GitHub. Did you delete it? So I'm answering via email.

On 9/13/23 20:09, Jaykishan wrote:
>
> Thank you for your response still I have few questions for my genome 
> which I am trying to forge it's not in 2bit format also if i give 
> single .gz file of genome is that fine or I have 11 chromosome so I 
> have to give individual chromosome in fasta can you please guide me 
> through genome format
>
You don't need to care about any of this if you use the 
forgeBSgenomeDataPkgFromNCBI() command I gave you earlier. Did it work?

Best,

H.

**Comment by JaykishanJ** [comment] 2023-09-22 14:58
Thank you so much @hpages  for this quick response it works fine but after this once I try to run my analysis on bam file it through me error because the BSGenome package which I have created contain chromosomes names something like this seqnames(BSgenome.Mmalaccensis.NCBI.ASM31385v2)
   [1] "chr1"          "chr2"          "chr3"          "chr4"
   [5] "chr5"          "chr6"          "chr7"          "chr8"
   [9] "chr9"          "chr10"         "chr11"         "scaffold_2638"
  [13] "scaffold_2639" "scaffold_2640" "scaffold_2641" "scaffold_2642"
  [17] "scaffold_2643" "scaffold_2644" "scaffold_2645" "scaffold_2646"
  [21] "scaffold_2647" "scaffold_2648" "scaffold_2649" "scaffold_2650"
  [25] "scaffold_2651" "scaffold_2652" "scaffold_2653" "scaffold_2654"
  [29] "scaffold_2655" "scaffold_2656" "scaffold_2657" "scaffold_2658"
  [33] "scaffold_2659" "scaffold_2660" "scaffold_2661" "scaffold_2662"
  [37] "scaffold_2663" "scaffold_2664" "scaffold_2665" "scaffold_2666"
  [41] "scaffold_2667" "scaffold_2668" "scaffold_2669" "scaffold_2670"
  [45] "scaffold_2671" "scaffold_2672" "scaffold_2673" "scaffold_2674"
  [49] "scaffold_2675" "scaffold_2676" "scaffold_2677" "scaffold_2678"
  [53] "scaffold_2679" "scaffold_2680" "scaffold_2681" "scaffold_2682"
  [57] "scaffold_2683" "scaffold_2684" "scaffold_2685" "scaffold_2686"
  [61] "scaffold_2687" "scaffold_2688" "scaffold_2689" "scaffold_2690"
  [65] "scaffold_2691" "scaffold_2692" "scaffold_2693" "scaffold_2694"
  [69] "scaffold_2695" "scaffold_2696" "scaffold_2697" "scaffold_2698"
  [73] "scaffold_2699" "scaffold_2700" "scaffold_2701" "scaffold_2702"
  [77] "scaffold_2703" "scaffold_2704" "scaffold_2705" "scaffold_2706"
  [81] "scaffold_2707" "scaffold_2708" "scaffold_2709" "scaffold_2710"
  [85] "scaffold_2711" "scaffold_2712" "scaffold_2713" "scaffold_2714"



On other hand in my bam file it's look like this 

Rsamtools::idxstatsBam("/data/003_NGS_research_projects/NGS_220464_Methylation/Qsea/G1.sorted.bam")
           seqnames seqlength  mapped unmapped
1                 *         0       0   498980
2       NC_025202.1  27573629 2654784    57473
3       NC_025203.1  22054697 1984392    42898
4       NC_025204.1  30470407 2809102    61262
5       NC_025205.1  30051516 2382614    53226
6       NC_025206.1  29377369 2683825    59131
7       NC_025207.1  34899179 3299567    70319
8       NC_025208.1  28617404 2879198    62294
9       NC_025209.1  35439739 3809463    80768
10      NC_025210.1  34148863 3361091    73835
11      NC_025211.1  33665772 4205183    83254
12      NC_025212.1  25514024 2509415    55657
13   NW_008990485.1      4262    1990       39
14   NW_008990486.1      4261     334       11
15   NW_008990487.1      4260    2135       31
16   NW_008990488.1      4260    1150       23
17   NW_008990489.1      4257      82       13
18   NW_008990490.1      4256     638       17
19   NW_008990491.1      4254     353        6
20   NW_008990492.1      4253      35        1
21   NW_008990493.1      4249    1307       17
22   NW_008990494.1      4248     127        3




So can you guide me to the solution for the same 


Thank you

**Comment by hpages** [comment] 2023-09-22 16:01
Hi,

The **BSgenome.Mmalaccensis.NCBI.ASM31385v2** package contains the official sequence names of the ASM31385v2 assembly, but it looks like your BAM files use the RefSeq accession numbers instead. You can use the `getChromInfoFromNCBI()` utility in **GenomeInfoDb** to obtain a data.frame that shows the mapping between the official names (the `SequenceName` column) and the RefSeq accessions (the `RefSeqAccn` column):
```
library(GenomeInfoDb)
chrominfo <- getChromInfoFromNCBI("GCF_000313855.2")
chrominfo[1:5, ]
#   SequenceName       SequenceRole AssignedMolecule GenBankAccn Relationship
# 1         chr1 assembled-molecule             <NA>  HE813975.1            =
# 2         chr2 assembled-molecule             <NA>  HE813976.1            =
# 3         chr3 assembled-molecule             <NA>  HE813977.1            =
# 4         chr4 assembled-molecule             <NA>  HE813978.1            =
# 5         chr5 assembled-molecule             <NA>  HE813979.1            =
#    RefSeqAccn     AssemblyUnit SequenceLength UCSCStyleName circular
# 1 NC_025202.1 Primary Assembly       27573629          <NA>       NA
# 2 NC_025203.1 Primary Assembly       22054697          <NA>       NA
# 3 NC_025204.1 Primary Assembly       30470407          <NA>       NA
# 4 NC_025205.1 Primary Assembly       30051516          <NA>       NA
# 5 NC_025206.1 Primary Assembly       29377369          <NA>       NA
```

You can rename the sequences in **BSgenome.Mmalaccensis.NCBI.ASM31385v2** with the small helper function below:
```
renameToRefSeq <- function(genome) {
    chrominfo <- getChromInfoFromNCBI("GCF_000313855.2")
    m <- match(seqlevels(genome), chrominfo$SequenceName)
    stopifnot(all(seqlengths(genome) == chrominfo$SequenceLength[m]))  # sanity check
    seqlevels(genome) <- chrominfo$RefSeqAccn[m]
    genome
}
```
Then:
```
library(BSgenome.Mmalaccensis.NCBI.ASM31385v2)
genome <- BSgenome.Mmalaccensis.NCBI.ASM31385v2
genome <- renameToRefSeq(genome)
seqinfo(genome)
# Seqinfo object with 7259 sequences from ASM31385v2 genome:
#   seqnames       seqlengths isCircular     genome
#   NC_025202.1      27573629      FALSE ASM31385v2
#   NC_025203.1      22054697      FALSE ASM31385v2
#   NC_025204.1      30470407      FALSE ASM31385v2
#   NC_025205.1      30051516      FALSE ASM31385v2
#   NC_025206.1      29377369      FALSE ASM31385v2
#   ...                   ...        ...        ...
#   NW_008997729.1       2308      FALSE ASM31385v2
#   NW_008997730.1       2180      FALSE ASM31385v2
#   NW_008997731.1       2136      FALSE ASM31385v2
#   NW_008997732.1       2055      FALSE ASM31385v2
#   NW_008997733.1       2015      FALSE ASM31385v2
```
Note that the renaming is not persistent i.e. the **BSgenome.Mmalaccensis.NCBI.ASM31385v2** package still contains the original sequence names. In other words, you need to perform the renaming each time you run your analysis. 

Hope this helps,

H.

**Comment by hpages** [comment] 2023-09-26 15:34
Did that help? Can we close this?

**Closed as completed** 2023-10-05 18:14 UTC

**Comment by JaykishanJ** [comment] 2023-11-18 07:01
hi @hpages  even after changing the name when i used to run for the same then it throughs me error 


650.1, NW_008997651.1, NW_008997652.1, NW_008997653.1, NW_008997654.1, NW_008997655.1, NW_008997656.1, NW_008997657.1, NW_008997658.1, NW_008997659.1, NW_008997660.1, NW_008997661.1, NW_008997662.1, NW_008997663.1, NW_008997664.1, NW_008997665.1, NW_008997666.1, NW_008997667.1, NW_008997668.1, NW_008997669.1, NW_008997670.1, NW_008997671.1, NW_008997672.1, NW_008997673.1, NW_008997674.1, NW_008997675.1, NW_008997676.1, NW_008997677.1, NW_008997678.1, NW_008997679.1, NW_008997680.1, NW_008997681.1, NW_008997682.1, NW_008997683.1, NW_008997684.1, NW_008997685.1, NW_008997686.1, NW_008997687.1, NW_008997688.1, NW_008997689.1, NW_008997690.1, NW_008997691.1, NW_008997692.1, NW_008997693.1, NW_008997694.1, NW_008997695.1, NW_008997696.1, NW_008997697.1, NW_008997698.1, NW_008997699.1, NW_008997700.1, NW_008997702.1, NW_008997703.1, NW_008997704.1, NW_008997705.1, NW_008997706.1, NW_008997707.1, NW_008997708.1, NW_008997709.1, NW_008997710.1, NW_008997711.1, NW_008997712.1, NW_008997713.1, NW_008997714.1, NW_008997715.1, NW_008997716.1, NW_008997717.1, NW_008997718.1, NW_008997719.1, NW_008997720.1, NW_008997721.1, NW_008997722.1, NW_008997723.1, NW_008997724.1, NW_008997725.1, NW_008997726.1, NW_008997727.1, NW_008997728.1, NW_008997729.1, NW_008997730.1, NW_008997731.1, NW_008997732.1, NW_008997733.1
Error in as.character.default(X[[i]], ...) :
  no method for coercing this S4 class to a vector
> qseaSet

**Comment by hpages** [comment] 2023-11-18 19:52
Please open a new issue and describe precisely what the problem is. You need to show the exact steps that lead to the above error (including the exact commands you used to perform these steps + their outpout), and your `sessionInfo()`.
